In [1]:
import numpy as n

In [5]:
a = n.arange(1,11,1)

In [6]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
b = n.arange(2,12,1)

In [8]:
print(b)

[ 2  3  4  5  6  7  8  9 10 11]


In [11]:
print(a*b)

[  2   6  12  20  30  42  56  72  90 110]
