In [32]:
import numpy as n

In [33]:
a = n.arange(16).reshape(4,4)

In [34]:
b = n.copy(a)

In [35]:
b[[0,-1]] = b[[-1,0]]

In [40]:
print(f"Original array\n\n {a}")

Original array

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [41]:
print(f"Swaped array\n\n {b}")

Swaped array

 [[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
